const shops = [
  { id: 1, name: 'Sharetea Belmar', region: 'West', address: '424 S Teller St, Lakewood, CO 80226', website: ''},
  { id: 2, name: 'Sharetea Westminster', region: 'Northwest', address: '5684 W 88th Ave, Westminster, CO 80031', website: ''},
  { id: 3, name: 'Sharetea Aurora', region: 'East', address: '2495 S Havana St, Suite #D, Aurora, CO 80014', website: ''},
  { id: 4, name: 'Sharetea Highlands Ranch', region: 'Southwest', address: '9579 S University Blvd #180, Highlands Ranch, CO 80126', website: ''},
  { id: 5, name: 'Kung Fu Tea Littleton', region: 'Southwest', address: '8555 W Belleview Ave Ste G21, Littleton, CO 80123', website: ''},
  { id: 6, name: 'Kung Fu Tea Denver', region: 'East', address: '6365 E Hampden Ave #102, Denver, CO 80222', website: ''},
  { id: 7, name: 'Kung Fu Tea Highlands Ranch', region: 'Southwest', address: '9559 S University Blvd, Unit 107, Highlands Ranch, CO 80126', website: ''},
  { id: 8, name: 'Kung Fu Tea Aurora', region: 'East', address: '12201 E Mississippi Ave, #123A, Aurora, CO 80012', website: ''},
  { id: 9, name: 'Kung Fu Tea Northfield', region: 'East', address: '8302 E Northfield Blvd Unit 1580, Denver, CO 80238', website: ''},
  { id: 10, name: 'Kung Fu Tea Centennial', region: 'DTC', address: '20209 E. Smoky Hill Road, Suite A2, Centennial, CO 80015', website: ''},
  { id: 11, name: 'Kung Fu Tea Thornton', region: 'North', address: '13571 Grant Street, Denver, CO 80241', website: ''},
  { id: 12, name: 'KUTEA', region: 'West', address: '1147 S Federal Blvd, Denver, CO 80219', website: ''},
  { id: 13, name: 'Boba Chic', region: 'West', address: '655 S Federal Blvd, Denver, CO 80219', website: ''},
  { id: 14, name: 'Arden', region: 'Southwest', address: '3355 S Yarrow St Unit E-115, Lakewood, CO 80227', website: ''},
  { id: 15, name: 'Lollicup', region: 'West', address: '1046 S Federal Blvd, Denver, CO 80219', website: ''},
  { id: 16, name: 'Lollicup', region: 'Central', address: '1589 S Colorado Blvd, Glendale, CO 80246', website: ''},
  { id: 17, name: 'Boba Zone', region: 'Southwest', address: '5005 S Kipling Pkwy Unit A8, Littleton, CO 80127', website: ''},
  { id: 18, name: 'Mo Mo Tea House', region: 'Southwest', address: '3602 River Point Pkwy Unit C, Englewood, CO 80110', website: ''},
  { id: 19, name: 'Boba & Crepes', region: 'Central', address: '4085 E Mississippi Ave D2, Denver, CO 80246', website: ''},
  { id: 20, name: 'Master Tea', region: 'Northwest', address: '6600 W 120th Ave, Unit I, Brooomfield, CO, 80020', website: ''},
  { id: 21, name: 'Master Tea', region: 'North', address: '2205 W 136th Ave, Suite 100, Broomfield, CO 80023', website: ''},
  { id: 22, name: 'Tea Street', region: 'Central', address: '4090 E Mississippi Ave, Denver, CO 80246', website: ''},
  { id: 23, name: 'Colorado Tea Station', region: 'Central', address: '1700 Platte St #130, Denver, CO 80202', website: ''},
  { id: 24, name: 'Milk Tea People', region: 'Central', address: '1641 Market St Suite 133, Denver, CO 80202', website: ''},
  { id: 25, name: 'Dingtea Denver', region: 'Central', address: '1699 S Colorado Blvd Unit E, Denver, CO 80222', website: ''},
  { id: 26, name: 'Hype Tea', region: 'Northwest', address: '6350 Sheridan Boulevard, Unit #105A, Arvada, CO 80003', website: ''},
  { id: 27, name: 'TBAAR', region: 'Central', address: '3970 Buchtel Blvd S Ste 105, Denver, CO 80210', website: ''},
  { id: 28, name: 'Like Tea', region: 'Southeast', address: '8433 Park Meadows Center Dr Suite D144A, Lone Tree, CO 80124', website: ''},
  { id: 29, name: 'Mini Moo\'s Tea Shop', region: 'Southeast', address: '7555 E Arapahoe Rd # 1, Centennial, CO 80112', website: ''},
  { id: 30, name: 'Happy Lemon Edgewater', region: 'West', address: '1931 Sheridan Boulevard Unit Q, Edgewater, CO 80214', website: ''},
  { id: 31, name: 'Happy Lemon 120th', region: 'North', address: '1001 W 120th Ave Suite 105, Westminster, CO 80234', website: ''},
  { id: 32, name: 'Happy Lemon Greenwood Village', region: 'Southeast', address: '9686 E Arapahoe Rd Unit B, Greenwood Village, CO 80112', website: ''},
  { id: 33, name: 'Zero Degrees Denver', region: 'Central', address: '1390 S Colorado Blvd Suite 140, Denver, CO 80222', website: ''},
  { id: 34, name: 'Zero Degrees Thornton', region: 'North', address: '9760 Grant St Ste 70, Thornton, CO 80229', website: ''},
  { id: 35, name: 'Zero Degrees Aurora', region: 'East', address: '13600 E Colfax Ave, Aurora, CO 80011', website: ''},
  { id: 36, name: 'Spill the Tea', region: 'North', address: '1040 W 104th Ave, Northglenn, CO 80234', website: ''},
  { id: 37, name: 'Yomie\'s Rice x Yogurt', region: 'Central', address: '1350 S Colorado Blvd #121, Denver, CO 80222', website: ''},
  { id: 38, name: 'BeauTea Bubbles', region: 'Central', address: '723 Quebec St, Denver, CO 80220', website: ''},
  { id: 39, name: 'Devil & Angel Desserts', region: 'East', address: '2727 S Parker Rd, Aurora, CO 80014', website: ''},
  { id: 40, name: 'Volcano Tea House', region: 'East', address: '2781 S Parker Rd, Aurora, CO 80014', website: ''},
  { id: 41, name: 'Banned Boba', region: 'East', address: '2790 S Havana St, Suite U, Aurora, CO 80014', website: ''},
  { id: 42, name: 'Tiger Sugar', region: 'East', address: '3105 S Peoria St, Unit C, Aurora, CO 80014', website: ''},
  { id: 43, name: 'SNOWL', region: 'East', address: '1930 S Havana St, #5-6, Aurora, CO 80014', website: ''},
  { id: 44, name: 'Boss Tea', region: 'East', address: '14101 E Exposition Ave, Aurora, CO 80012', website: ''},
  { id: 45, name: 'Tea Cloud & Poke', region: 'Central', address: '1690 Champa St, Denver, CO 80202', website: ''},
  { id: 46, name: 'SpeckleTea', region: 'Southwest', address: '9956 W Remington Pl Unit A4, Littleton, CO 80128', website: ''},
  { id: 47, name: 'Bambu Che, Coffee, and Teas', region: 'Central', address: '2215 S Broadway, Denver, CO 80210', website: ''},
  { id: 48, name: 'WeeTea', region: 'Northwest', address: '8410 Wadsworth Boulevard, Unit H-S, Arvada, CO 80003', website: ''},
  { id: 49, name: '528Tea', region: 'Northwest', address: '7639 W 88th Ave, Westminster, CO 80005', website: ''},
  { id: 50, name: 'Wonder Tea Cafe', region: 'East', address: '12303 E Mississippi Ave Unit 141, Aurora, CO 80012', website: ''},
  { id: 51, name: 'Mochinut', region: 'East', address: '2222 S Havana St Unit A2, Aurora, CO 80014', website: ''},
  { id: 52, name: 'Boba Touch', region: 'Central', address: '3107 E Colfax Ave, Denver, CO 80206', website: ''},
  { id: 53, name: 'Milkit', region: 'Southeast', address: '9625 E Arapahoe Rd Unit G, Greenwood Village, CO 80112', website: ''},
  { id: 54, name: 'Tsaocaa Wesminster', region: 'Northwest', address: '5092 W 92nd Ave, Westminster, CO 80031', website: ''},
  { id: 55, name: 'The Alley at Southlands', region: 'Southeast', address: '24107 E Commons Ave Ste 102, Aurora, CO 80016', website: ''},
  { id: 56, name: 'Tea-hee Boba', region: 'North', address: '3894 E 120th Ave Unit B, Thornton, CO 80233', website: ''},
  { id: 57, name: 'Kung Fu Tea Wheat Ridge', region: 'West', address: '3400 Youngfield St, Wheat Ridge, CO 80033', website: ''},
  { id: 58, name: 'Plentea', region: 'North', address: '1391 E 120th Ave D, Thornton, CO 80233', website: ''},
  { id: 59, name: 'Colorado Boba Blast', region: 'Central', address: '1559 S Broadway, Denver, CO 80223', website: ''},
  { id: 60, name: 'PRESOTEA AURORA', region: 'Southeast', address: '18662 E Hampden Ave, Aurora, CO 80013', website: ''},
  { id: 61, name: 'Milk T Boba House', region: 'West', address: '902 Federal Blvd, Denver, CO 80204', website: 'https://www.milktdenver.com/'},
  { id: 62, name: 'Boba Boba Arvada', region: 'Northwest', address: '6474 Ward Rd, Arvada, CO 80004', website: ''},
]

module.exports = shops; 

// Prior to 2017, there were give or take 5 boba/milk tea shops in the DMA. 
// Now, there are well over 60 stand-alone shops that feature boba or milk tea as a significant part of their menu.

// Personal stats: 48/62 shops = 77.4%